import * as Types from '../../../../../__generated__/graphTypesGenerated';

import { TypedDocumentNode as DocumentNode } from '@apollo/client';
export type GetPokemonListQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type GetPokemonListQuery = { pokemons: Array<{ __typename: 'pokemon', myNewField: string | null, name: string, id: number, sprites: Array<{ __typename: 'pokemonsprites', sprites: unknown }>, pokemonsprites: Array<{ __typename: 'pokemonsprites', sprites: unknown }>, types: Array<{ __typename: 'pokemontype', slot: number, type: { __typename: 'type', name: string, id: number } | null }> }> };


export const GetPokemonListDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetPokemonList"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":{"kind":"Name","value":"pokemons"},"name":{"kind":"Name","value":"pokemon"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"order_by"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"id"},"value":{"kind":"EnumValue","value":"asc"}}]}},{"kind":"Argument","name":{"kind":"Name","value":"limit"},"value":{"kind":"IntValue","value":"10"}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"BasePokemon"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"BasePokemon"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"pokemon"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","alias":{"kind":"Name","value":"sprites"},"name":{"kind":"Name","value":"pokemonsprites"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"sprites"}}]}},{"kind":"Field","name":{"kind":"Name","value":"pokemonsprites"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"sprites"}}]}},{"kind":"Field","name":{"kind":"Name","value":"myNewField"},"directives":[{"kind":"Directive","name":{"kind":"Name","value":"client"}}]},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","alias":{"kind":"Name","value":"types"},"name":{"kind":"Name","value":"pokemontypes"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"slot"}},{"kind":"Field","name":{"kind":"Name","value":"type"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"id"}}]}}]}}]}}]} as unknown as DocumentNode<GetPokemonListQuery, GetPokemonListQueryVariables>;