import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
	overwrite: true,
	schema: "https://graphql.pokeapi.co/v1beta2",
	documents: ["app/**/*.gql"],
  
	generates: {
		"__generated__/graphTypesGenerated.ts": {
			plugins: ["typescript"],
			config: {
      				// Use `unknown` instead of `any` for unconfigured scalars
				defaultScalarType: "unknown",
			}
		},
		"./app/": {
			preset: "near-operation-file",
			presetConfig: {
				// This should be the file generated by the "typescript" plugin above,
				// relative to the directory specified for this configuration
				baseTypesPath: "./__generated__/graphTypesGenerated.ts",
			},
			plugins: ["typescript-operations", "typed-document-node"],
			// Note: these config options moved from the other generated file config
			config: {
				avoidOptionals: {
					// Use `null` for nullable fields instead of optionals
					field: true,
					// Allow nullable input fields to remain unspecified
					inputValue: false,
				},
				// Use `unknown` instead of `any` for unconfigured scalars
				defaultScalarType: "unknown",
				// Apollo Client always includes `__typename` fields
				nonOptionalTypename: true,
				// Apollo Client doesn't add the `__typename` field to root types so
				// don't generate a type for the `__typename` for root operation types.
				skipTypeNameForRoot: true,
			},
		},
	},
};

export default config;
